address montonic and prediction size issues
davidwilby/deepsensor pull request #8
Opened 2024-09-17 13:57 UTC by MartinSJRogers

This PR addresses the monotonic and prediction size issues. It tries to address these instead of using the previous PRs on this issue: #7 and #6

2024-10-11 18:48 UTC, davidwilby requested changes
Lets merge this, only one change suggested to a comment. Let's close the other PRs as well. Nice one.

2024-10-11 18:48 UTC, davidwilby commented on deepsensor/model/model.py
> +                            # This line, as well as 933, 940 and 950 address the different shapes between the input and prediction
```suggestion
                            # The +1 operations here and elsewhere in this block address the different shapes between the input and prediction
```

2024-10-11 18:48 UTC, davidwilby commented on deepsensor/model/model.py
> +                            # TODO: Try to resolve this issue in data/loader.py by ensuring patches are perfectly square.
I'll look into this but let's merge this for now.

2024-10-15 12:46 UTC, MartinSJRogers reviewed
Change to code description agreed.

2024-10-15 12:54 UTC, davidwilby approved these changes
:rocket:

2024-10-15 12:55 UTC, MartinSJRogers commented
Happy to merging and close this PR as discussed. It is saying merging black my end- do you need to review Thinking out loud: in dataloader.py perhaps there is a location where we can assert that patched tasks have an equal size in `x1` and `x2`?

2024-10-15 12:58 UTC, merged